### PR TITLE
#252 Validate input in ExchangeEtherForDID

### PR DESCRIPTION
**Pull request by DK308**

### CODE REVIEW

**Comment by JohnAllen** [comment]
Hey @DK308, thanks for this PR!

Can you tell me where you got the `.18` exchange rate from?  The exchange rate is actually floating with the `didPerEther` parameter value. Reviewing more now.

**Comment by DK308** [comment]
sorry about that I fixed it in next commit. I was just using that for testing because I was getting undefined from this.props.didPerEtherExchangeRate function. If there is anything else i can modify in my PR just len me now :)

**Comment by JohnAllen** [comment]
Want to remove that `console.log`?

**Comment by DK308** [comment]
@JohnAllen I removed my `console.log` but I kept yours. Is everything else ok?

**Pull request merged**
