### PR TITLE
Closes #231: Add responsive hamburger menu

### LINKED ISSUE #231: Implement Responsive Hamburger Menu
Right now our mobile menu just displays the same menu items as the big window version.

So we need to stack the items into a clickable "hamburger" menu.

Note that Semantic-UI doesn't have a built-in option for this, and I found an npm package that was big.

So the solution is of course ideally simple and small.
screen shot 2018-04-18 at 11 19 08 am

### PR DESCRIPTION
**Pull request by anshumanv**
Workflow - 
* Made menu stackable
* Detect when the menu is stacked vertically, display a `bars` icon from react-icons package which is using fa icons.
* Simple toggle nav function on clicking the hamburger icon.

Todo - 
* Make it work for all routes.
* Stying of the bars icon

### CODE REVIEW

**Comment by anshumanv** [comment]
@JohnAllen have any other todo in mind?

**Comment by JohnAllen** [comment]
Hey @anshumanv attached is a preview of the behavior of your changes.  Is this what you intended?
screen shot 2018-05-06 at 6 11 59 pm

**Comment by JohnAllen** [comment]
Also it only works when you resize.  It doesn't work for when people just use mobile.  It only triggers the hamburger menu on resize, right?

**Comment by anshumanv** [comment]
> Hey @anshumanv attached is a preview of the behavior of your changes. Is this what you intended?


Hey, @JohnAllen thanks for checking that out, styling is yet to be done, I was just picking up the todos, I'll be centering them and a check on page load so it doesn't rely on resizing initially.

**Comment by anshumanv** [comment]
Any other preferences you have?

**Comment by JohnAllen** [comment]
No, just the standard hamburger menu is what I prefer.  Thanks.

What do you mean "centering" them?

**Comment by anshumanv** [comment]
Tha hamburger icon is sticking to one side, right? so I'll do some basic styling to make it look better. I thought maybe I should center align the `Distense` image the hamburger icon, and the DID count.

Do you want to keep them to the left side of the page as they are now? Both look good IMO. Or do you want to have them(Distense image, hamburger icon, and DID count) all horizontally aligned and not vertically(as they are now)?

**Comment by anshumanv** [comment]
Hey @JohnAllen :smile: 
I'm done implementing the approach I thought of, please pull the changes once and check locally if you need anything else to be added/changed.

**Comment by anshumanv** [comment]
In fact, I deployed an instance here - http://distense-ui.surge.sh/ for you to check things out quickly. :smile: 
Please add your feedback to that.

**Comment by JohnAllen** [comment]
Behaves better!

The hamburger icon should be top right corner and total DID should be in the center.  Thanks for deploying an instance of your code!

**Comment by JohnAllen** [comment]
We'll also need to clear the eventListener a la:

```
componentWillUnmount() {
    window.removeEventListener('resize', this.onResize.bind(this));
  }
```

**Comment by anshumanv** [comment]
Thanks for reviewing! :smile: 

> The hamburger icon should be top right corner and total DID should be in the center.

Making the appropriate styling changes.

> We'll also need to clear the eventListener

Ah, forgot :sweat_smile:, doing that right away. :smile:

**Comment by anshumanv** [comment]
@JohnAllen hey :wave: 

Done the changes you suggested, please check - http://distense.surge.sh/

I'm happy to make any other minor changes you have in mind, and do tell me if you need the commits squashed. :smile: 

I've been involved with Google Summer of Code stuff recently, thanks for your patience.

**Comment by JohnAllen** [comment]
Can we do one more thing?  Can you make the items drop down on the right under the hamburger menu?  Looks great otherwise!

**Comment by anshumanv** [comment]
@JohnAllen done! :smile: 

Up for merge! :tada: :rocket:

**Review by JohnAllen — APPROVED** [review]

**Pull request closed without merging**
